# Generated by Django 5.0.2 on 2024-02-29 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuarterbackSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the quarterback's name", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw_accuracy', models.IntegerField()),
                ('pocket_awareness', models.IntegerField()),
                ('arm_strength', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('history', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quarterback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.coach')),
                ('skillset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.skillset')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.team')),
            ],
        ),
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarterback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.quarterback')),
            ],
        ),
        migrations.CreateModel(
            name='CareerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField()),
                ('pass_attempts', models.IntegerField()),
                ('pass_completions', models.IntegerField()),
                ('pass_yards', models.IntegerField()),
                ('pass_touchdowns', models.IntegerField()),
                ('rush_yards', models.IntegerField()),
                ('rush_touchdowns', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('quarterback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.quarterback')),
            ],
        ),
    ]
