# Generated by Django 5.0.2 on 2024-03-01 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarterback_simulation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuarterbackSearch',
        ),
    ]
