# Generated by Django 5.0.2 on 2024-03-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarterback_simulation', '0003_remove_quarterback_coach_remove_quarterback_skillset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='halloffame',
            name='hof_status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
