# Generated by Django 5.0.2 on 2024-03-02 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarterback_simulation', '0004_halloffame_hof_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerStats_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField()),
                ('pass_attempts', models.IntegerField()),
                ('pass_completions', models.IntegerField()),
                ('pass_yards', models.IntegerField()),
                ('pass_touchdowns', models.IntegerField()),
                ('rush_yards', models.IntegerField()),
                ('rush_touchdowns', models.IntegerField()),
                ('interceptions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coach_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HallOfFame_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Quarterback_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('career_stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.careerstats_db')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.coach_db')),
            ],
        ),
        migrations.CreateModel(
            name='Skillset_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw_accuracy', models.IntegerField()),
                ('pocket_awareness', models.IntegerField()),
                ('arm_strength', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('history', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='careerstats',
            name='quarterback',
        ),
        migrations.DeleteModel(
            name='HallOfFame',
        ),
        migrations.AddField(
            model_name='halloffame_db',
            name='quarterback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.quarterback_db'),
        ),
        migrations.AddField(
            model_name='quarterback_db',
            name='skillset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.skillset_db'),
        ),
        migrations.AddField(
            model_name='quarterback_db',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.team_db'),
        ),
        migrations.DeleteModel(
            name='CareerStats',
        ),
        migrations.DeleteModel(
            name='Quarterback',
        ),
    ]
