# Generated by Django 5.0.2 on 2024-03-02 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarterback_simulation', '0005_careerstats_db_coach_db_halloffame_db_quarterback_db_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset_db',
            name='skills',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='halloffame_db',
            name='quarterback',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.quarterback_db'),
        ),
    ]
