# Generated by Django 5.0.2 on 2024-03-02 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarterback_simulation', '0006_skillset_db_skills_alter_halloffame_db_quarterback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillset_db',
            name='skills',
        ),
        migrations.AlterField(
            model_name='quarterback_db',
            name='coach',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.coach_db'),
        ),
        migrations.AlterField(
            model_name='quarterback_db',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.team_db'),
        ),
    ]
