# Generated by Django 5.0.2 on 2024-03-03 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarterback_simulation', '0007_remove_skillset_db_skills_alter_quarterback_db_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halloffame_db',
            name='quarterback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.quarterback_db'),
        ),
        migrations.AlterField(
            model_name='quarterback_db',
            name='career_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.careerstats_db'),
        ),
        migrations.AlterField(
            model_name='quarterback_db',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.coach_db'),
        ),
        migrations.AlterField(
            model_name='quarterback_db',
            name='skillset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.skillset_db'),
        ),
        migrations.AlterField(
            model_name='quarterback_db',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarterback_simulation.team_db'),
        ),
    ]
